In [3]:
import torch 
import torch.nn as nn
pixel_values = torch.randn(4, 3, 224, 224)
pixel_values.shape

torch.Size([4, 3, 224, 224])

In [5]:
conv = nn.Conv2d(in_channels = 3, out_channels = 768, kernel_size=16, stride=16, padding='valid')

In [8]:
conv(pixel_values).shape

torch.Size([4, 768, 14, 14])

In [10]:
conv(pixel_values).flatten(2).transpose(-2, -1).shape

torch.Size([4, 196, 768])

In [1]:
import torch

In [21]:
bias = torch.tril(torch.ones(size=(8,8)))
bias

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
x = torch.randn(size=(8,8))
x

tensor([[ 0.3784, -0.1677,  0.6594, -2.2096,  0.9106,  0.3928,  0.5163, -1.4784],
        [ 1.1493, -0.2649,  0.3257,  0.9281,  1.8215, -0.6997, -0.5771, -0.1153],
        [-1.0783,  0.0145, -0.6181, -0.0283,  0.6501, -0.1685, -0.3230,  0.3624],
        [-0.6954, -0.8433, -1.0251,  0.9460,  1.1891,  1.6096,  0.1554, -0.6210],
        [-0.1633,  1.4113, -0.5695, -1.4110, -0.4287,  1.8338,  0.0833,  0.4711],
        [-0.0108,  0.6817, -0.5105,  0.1147,  0.7083, -0.2359, -0.7061, -0.4890],
        [-2.1594, -0.2978, -0.9799,  1.0172, -0.1355, -0.8475,  0.3940, -0.0637],
        [-0.6191,  0.2975,  0.0156, -1.5250,  1.5943,  0.2346,  0.9808, -0.9203]])

In [23]:
a = x.masked_fill(bias== 0, float('-inf'))
a 

tensor([[ 0.3784,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 1.1493, -0.2649,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-1.0783,  0.0145, -0.6181,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.6954, -0.8433, -1.0251,  0.9460,    -inf,    -inf,    -inf,    -inf],
        [-0.1633,  1.4113, -0.5695, -1.4110, -0.4287,    -inf,    -inf,    -inf],
        [-0.0108,  0.6817, -0.5105,  0.1147,  0.7083, -0.2359,    -inf,    -inf],
        [-2.1594, -0.2978, -0.9799,  1.0172, -0.1355, -0.8475,  0.3940,    -inf],
        [-0.6191,  0.2975,  0.0156, -1.5250,  1.5943,  0.2346,  0.9808, -0.9203]])

In [25]:
torch.nn.functional.softmax(a, dim=-1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8044, 0.1956, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1796, 0.5358, 0.2846, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1291, 0.1114, 0.0929, 0.6666, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1325, 0.6397, 0.0882, 0.0380, 0.1016, 0.0000, 0.0000, 0.0000],
        [0.1317, 0.2633, 0.0799, 0.1494, 0.2704, 0.1052, 0.0000, 0.0000],
        [0.0170, 0.1095, 0.0553, 0.4077, 0.1287, 0.0632, 0.2186, 0.0000],
        [0.0435, 0.1088, 0.0821, 0.0176, 0.3981, 0.1022, 0.2155, 0.0322]])

In [17]:
tokens = [f"<loc{i:04d}>" for i in range(12)]
print(tokens)
tokens = [f"<seg{i:02d}>" for i in range(12)]
print(tokens)

['<loc0000>', '<loc0001>', '<loc0002>', '<loc0003>', '<loc0004>', '<loc0005>', '<loc0006>', '<loc0007>', '<loc0008>', '<loc0009>', '<loc0010>', '<loc0011>']
['<seg00>', '<seg01>', '<seg02>', '<seg03>', '<seg04>', '<seg05>', '<seg06>', '<seg07>', '<seg08>', '<seg09>', '<seg10>', '<seg11>']


In [ ]:
import torch 
torch.manual_seed(42)
tokens = torch.randint(low=0, high=25, size=(10,))
tokens 

tensor([17, 17,  1, 14,  1, 10, 20, 24,  0, 13])

In [9]:
text_mask = (tokens != 17) & (tokens != 13)
text_mask
image_mask = (tokens == 17)
image_mask
pad_mask = (tokens == 13)
print(f"{text_mask}\n{image_mask}\n{pad_mask}")

tensor([False, False,  True,  True,  True,  True,  True,  True,  True, False])
tensor([ True,  True, False, False, False, False, False, False, False, False])
tensor([False, False, False, False, False, False, False, False, False,  True])


In [30]:
# Shape: [Seq_Len, Embed_Dim] -> [10, 8]
text_mask_expanded = text_mask.unsqueeze(dim=-1).expand(-1, 8)
image_mask_expanded = image_mask.unsqueeze(dim=-1).expand(-1, 8)
pad_mask_expanded = pad_mask.unsqueeze(dim=-1).expand(-1, 8)
print(text_mask_expanded)

tensor([[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [False, False, False, False, False, False, False, False]])


In [ ]:
torch.manual_seed(42)
lookup = torch.randn(25, 8)
input_embeds = lookup[tokens]
print(input_embeds)

tensor([[ 1.1415e+00,  1.8565e-02, -1.8058e+00,  9.2543e-01, -3.7534e-01,
          1.0331e+00, -6.8665e-01,  6.3681e-01],
        [ 1.1415e+00,  1.8565e-02, -1.8058e+00,  9.2543e-01, -3.7534e-01,
          1.0331e+00, -6.8665e-01,  6.3681e-01],
        [-7.5214e-01,  1.6487e+00, -3.9248e-01, -1.4036e+00, -7.2788e-01,
         -5.5943e-01, -7.6884e-01,  7.6245e-01],
        [-1.4570e+00, -1.0234e-01, -5.9915e-01,  4.7706e-01,  7.2618e-01,
          9.1152e-02, -3.8907e-01,  5.2792e-01],
        [-7.5214e-01,  1.6487e+00, -3.9248e-01, -1.4036e+00, -7.2788e-01,
         -5.5943e-01, -7.6884e-01,  7.6245e-01],
        [ 1.0868e-02, -3.3874e-01, -1.3407e+00, -5.8537e-01,  5.3619e-01,
          5.2462e-01,  1.1412e+00,  5.1644e-02],
        [-1.9006e+00,  2.2858e-01,  2.4859e-02, -3.4595e-01,  2.8683e-01,
         -7.3084e-01,  1.7482e-01, -1.0939e+00],
        [ 2.6178e-01, -7.5993e-01, -2.0461e+00, -1.5295e+00,  4.0487e-01,
          6.3188e-01,  3.1253e-01, -3.3502e-02],
        [ 1.9269

In [37]:
torch.manual_seed(2)
image_features = torch.randn(4, 8)
image_features 

tensor([[-1.0408,  0.9166, -1.3042, -1.1097, -1.2188,  1.1676, -1.0574, -0.1188],
        [-0.9078,  0.3452, -0.5713, -0.2351,  1.0076, -0.7529, -0.2250, -0.4327],
        [-1.5071, -0.4586, -0.8480,  0.5266,  0.0299, -0.0498,  1.0651,  0.8860],
        [ 0.4640, -0.4986,  0.1289,  2.7631,  0.1405,  1.1191,  0.3152,  1.7528]])

In [28]:
final_embeddings = torch.zeros(10, 8)
final_embeddings = torch.where(condition=text_mask_expanded, input=input_embeds, other=final_embeddings)
final_embeddings

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [-1.4570, -0.1023, -0.5992,  0.4771,  0.7262,  0.0912, -0.3891,  0.5279],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [ 0.0109, -0.3387, -1.3407, -0.5854,  0.5362,  0.5246,  1.1412,  0.0516],
        [-1.9006,  0.2286,  0.0249, -0.3460,  0.2868, -0.7308,  0.1748, -1.0939],
        [ 0.2618, -0.7599, -2.0461, -1.5295,  0.4049,  0.6319,  0.3125, -0.0335],
        [ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [41]:
final_embeddings = final_embeddings.masked_scatter(mask=image_mask_expanded, source=image_features)
final_embeddings

tensor([[-1.0408,  0.9166, -1.3042, -1.1097, -1.2188,  1.1676, -1.0574, -0.1188],
        [-0.9078,  0.3452, -0.5713, -0.2351,  1.0076, -0.7529, -0.2250, -0.4327],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [-1.4570, -0.1023, -0.5992,  0.4771,  0.7262,  0.0912, -0.3891,  0.5279],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [ 0.0109, -0.3387, -1.3407, -0.5854,  0.5362,  0.5246,  1.1412,  0.0516],
        [-1.9006,  0.2286,  0.0249, -0.3460,  0.2868, -0.7308,  0.1748, -1.0939],
        [ 0.2618, -0.7599, -2.0461, -1.5295,  0.4049,  0.6319,  0.3125, -0.0335],
        [ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [42]:
torch.where(pad_mask_expanded, input=torch.zeros_like(final_embeddings), other=final_embeddings)

tensor([[-1.0408,  0.9166, -1.3042, -1.1097, -1.2188,  1.1676, -1.0574, -0.1188],
        [-0.9078,  0.3452, -0.5713, -0.2351,  1.0076, -0.7529, -0.2250, -0.4327],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [-1.4570, -0.1023, -0.5992,  0.4771,  0.7262,  0.0912, -0.3891,  0.5279],
        [-0.7521,  1.6487, -0.3925, -1.4036, -0.7279, -0.5594, -0.7688,  0.7624],
        [ 0.0109, -0.3387, -1.3407, -0.5854,  0.5362,  0.5246,  1.1412,  0.0516],
        [-1.9006,  0.2286,  0.0249, -0.3460,  0.2868, -0.7308,  0.1748, -1.0939],
        [ 0.2618, -0.7599, -2.0461, -1.5295,  0.4049,  0.6319,  0.3125, -0.0335],
        [ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784, -1.2345, -0.0431, -1.6047],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])